const pages=[['resumen','Resumen General'],['requisitos','Requisitos'],['pruebas','Casos de Prueba'],['cobertura','Cobertura'],['preguntas','Preguntas'],['defectos','Defectos'],['roadmap','Mejoras Roadmap'],['riesgos','Riesgos y Alertas'],['evolutivos','Evolutivos'],['documentos','Documentos']];
const sortState={};
const configs={requirements:{filters:['module','priority','diagnosis'],heads:['REQ','Descripción','Módulo','Prioridad','TC asociados','Nº','Diagnóstico'],row:r=>[r.id,r.description,r.module,r.priority,r.cases,r.count,r.diagnosis]},tests:{filters:['module','automation','via'],heads:['TC','REQ','Módulo','Prioridad REQ','Vía','Automatización','Objetivo específico'],row:r=>[r.id,r.req,r.module,r.priority,r.via,r.automation,r.objective]},coverage:{filters:['module','priority','verification'],heads:['REQ','Descripción','Módulo','Prioridad','TC asociados','Nº','Diagnóstico','Verificación'],row:r=>[r.id,r.description,r.module,r.priority,r.cases,r.count,r.diagnosis,r.verification]},questions:{filters:['status','source','area','impact'],heads:['ID','Pregunta','Estado','Respuesta','Origen','Ámbito','Impacto'],row:r=>[r.id,r.question,r.status,r.answer,r.source,r.area,r.impact]},bugs:{filters:['level'],heads:['ID','Defecto','Nivel'],row:r=>[r.id,r.title,r.level]},roadmap:{filters:['status'],heads:['ID','Mejora','Estado'],row:r=>[r.id,r.title,r.status]},risks:{filters:['level','category'],heads:['Riesgo','Categoría','Cantidad','Nivel','Acción recomendada'],row:r=>[r.risk,r.category,r.count,r.level,r.action]},evolutions:{filters:['status','effort','gate'],heads:['ID','Título','Estado','REQ afectados','Esfuerzo','Gate','Riesgo'],row:r=>[r.id,r.title,r.status,r.req,r.effort,r.gate,r.risk]},documents:{filters:['type','area'],heads:['Documento','Tipo','Ámbito','Versión','Origen'],row:r=>[r.name,r.type,r.area,r.version,r.content]}};
function init(){let n=document.getElementById('nav');pages.forEach(([id,label],i)=>{let b=document.createElement('button');b.textContent=label;b.className=i?'':'active';b.onclick=()=>{document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active')};n.appendChild(b)});document.querySelectorAll('Filters').forEach(x=>buildFilters(x));document.querySelectorAll('Summary').forEach(x=>{x.outerHTML='<div class="summary">'+x.getAttribute('labels').split(',').map((l,i)=>`<div class="card"><span class="muted">${l}</span><b data-kpi="${i}">0</b></div>`).join('')+'</div>'});document.querySelectorAll('Table').forEach(x=>buildTable(x));drawSummary()}
function buildFilters(x){let k=x.getAttribute('kind'),c=configs[k];x.outerHTML=`<div class="filters" data-filters="${k}">${c.filters.map(f=>{const values=[...new Set(data[k].map(r=>String(r[f])))].sort((a,b)=>a.localeCompare(b,'es',{numeric:true}));return `<div class="multi-filter" data-field="${f}"><button type="button" class="multi-toggle"><span>Todos · ${f}</span><b>⌄</b></button><div class="multi-options"><label><input type="checkbox" data-all checked> Todos</label>${values.map(v=>`<label><input type="checkbox" value="${v.replace(/"/g,'&quot;')}"> ${v}</label>`).join('')}</div></div>`}).join('')}<input placeholder="Buscar${k==='documents'?' documentos':'...'}" data-search><button type="button" data-clear>Limpiar filtros</button></div>`;let box=document.querySelector(`[data-filters="${k}"]`);box.querySelectorAll('.multi-toggle').forEach(btn=>btn.onclick=e=>{e.stopPropagation();const host=btn.closest('.multi-filter');document.querySelectorAll('.multi-filter.open').forEach(m=>{if(m!==host)m.classList.remove('open')});host.classList.toggle('open')});box.querySelectorAll('.multi-options').forEach(o=>o.onclick=e=>e.stopPropagation());box.querySelectorAll('.multi-options input').forEach(ch=>ch.onchange=()=>{const host=ch.closest('.multi-filter'),all=host.querySelector('[data-all]'),items=[...host.querySelectorAll('input:not([data-all])')];if(ch===all&&all.checked)items.forEach(i=>i.checked=false);if(ch!==all&&ch.checked)all.checked=false;if(ch!==all&&!items.some(i=>i.checked))all.checked=true;const selected=items.filter(i=>i.checked).map(i=>i.value),label=host.querySelector('.multi-toggle span');label.textContent=all.checked?`Todos · ${host.dataset.field}`:(selected.length<=2?selected.join(', '):`${selected.length} seleccionados`);render(k)});box.querySelector('[data-search]').oninput=()=>render(k);box.querySelector('[data-clear]').onclick=()=>{box.querySelector('[data-search]').value='';box.querySelectorAll('.multi-filter').forEach(host=>{host.querySelector('[data-all]').checked=true;host.querySelectorAll('input:not([data-all])').forEach(i=>i.checked=false);host.querySelector('.multi-toggle span').textContent=`Todos · ${host.dataset.field}`});render(k)};document.addEventListener('click',()=>document.querySelectorAll('.multi-filter.open').forEach(m=>m.classList.remove('open')), {once:false})}
function buildTable(x){let k=x.getAttribute('kind'),c=configs[k];if(!c)return;x.outerHTML=`<div class="card"><div class="table-wrap"><table data-kind="${k}"><thead><tr>${c.heads.map((h,i)=>`<th data-sort-kind="${k}" data-sort-index="${i}">${h}<span class="sort-mark"></span></th>`).join('')}</tr></thead><tbody data-body="${k}"></tbody></table></div></div>`;document.querySelectorAll(`th[data-sort-kind="${k}"]`).forEach(th=>th.onclick=()=>sortBy(k,+th.dataset.sortIndex));render(k)}
function sortBy(k,index){const current=sortState[k];sortState[k]={index,dir:current&&current.index===index&&current.dir==='asc'?'desc':'asc'};render(k)}function smartCompare(a,b){const na=parseFloat(String(a).replace(/[^0-9.-]/g,'')),nb=parseFloat(String(b).replace(/[^0-9.-]/g,''));if(!Number.isNaN(na)&&!Number.isNaN(nb)&&String(a).match(/\d/)&&String(b).match(/\d/))return na-nb;return String(a).localeCompare(String(b),'es',{numeric:true,sensitivity:'base'})}function rows(k){let box=document.querySelector(`[data-filters="${k}"]`),q=box?.querySelector('[data-search]').value.toLowerCase()||'';let result=data[k].filter(r=>{const matchesMulti=[...(box?.querySelectorAll('.multi-filter')||[])].every(host=>{const all=host.querySelector('[data-all]').checked,selected=[...host.querySelectorAll('input:not([data-all]):checked')].map(i=>i.value);return all||!selected.length||selected.includes(String(r[host.dataset.field]))});return matchesMulti&&(!q||Object.values(r).join(' ').toLowerCase().includes(q))});const st=sortState[k];if(st){const fn=configs[k].row;result.sort((a,b)=>smartCompare(fn(a)[st.index],fn(b)[st.index])*(st.dir==='asc'?1:-1))}return result}
function normValue(v){return String(v??'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function coloredPill(value,cssClass){return `<span class="status-pill ${cssClass}">${value}</span>`}
function formatCell(kind,index,value){
 const n=normValue(value);
 // Requisitos: Prioridad (index 3)
 if(kind==='requirements'&&index===3){if(n==='critical')return coloredPill(value,'status-critical');if(n==='high')return coloredPill(value,'status-high');if(n==='medium')return coloredPill(value,'status-medium');if(n==='low')return coloredPill(value,'status-low')}
 // Casos de prueba: Prioridad REQ (index 3) y Automatización (index 5)
 if(kind==='tests'&&index===3){if(n==='critical')return coloredPill(value,'status-critical');if(n==='high')return coloredPill(value,'status-high');if(n==='medium')return coloredPill(value,'status-medium');if(n==='low')return coloredPill(value,'status-low')}
 if(kind==='tests'&&index===5){if(n==='high')return coloredPill(value,'status-good');if(n==='medium')return coloredPill(value,'status-medium');if(n==='low')return coloredPill(value,'status-low');if(n==='not recommended')return coloredPill(value,'status-critical')}
 // Cobertura: Prioridad (index 3), Diagnóstico (index 6), Verificación (index 7)
 if(kind==='coverage'&&index===3){if(n==='critical')return coloredPill(value,'status-critical');if(n==='high')return coloredPill(value,'status-high');if(n==='medium')return coloredPill(value,'status-medium');if(n==='low')return coloredPill(value,'status-low')}
 if(kind==='coverage'&&index===6)return coloredPill(value,n==='correcto'?'status-good':'status-bad');
 if(kind==='coverage'&&index===7)return coloredPill(value,n==='completa'?'status-good':'status-bad');
 // Preguntas: Impacto (index 6)
 if(kind==='questions'&&index===6){if(n==='alto')return coloredPill(value,'status-high');if(n==='medio')return coloredPill(value,'status-medium');if(n==='bajo')return coloredPill(value,'status-low')}
 // Defectos: Nivel/Severidad (index 2). Admite valores en español o inglés.
 if(kind==='bugs'&&index===2){if(n==='critical'||n==='critico'||n==='critica')return coloredPill(value,'status-critical');if(n==='high'||n==='alto'||n==='alta')return coloredPill(value,'status-high');if(n==='medium'||n==='medio'||n==='media')return coloredPill(value,'status-medium');if(n==='low'||n==='bajo'||n==='baja')return coloredPill(value,'status-low')}
 // Mejoras Roadmap: Estado (index 2)
 if(kind==='roadmap'&&index===2){if(n==='accepted'||n==='aceptado'||n==='aceptada')return coloredPill(value,'status-accepted');if(n==='proposed'||n==='propuesto'||n==='propuesta')return coloredPill(value,'status-proposed')}
 // Riesgos y Alertas: Nivel (index 3)
 if(kind==='risks'&&index===3){if(n==='critical'||n==='critico'||n==='critica')return coloredPill(value,'status-critical');if(n==='high'||n==='alto'||n==='alta')return coloredPill(value,'status-high');if(n==='medium'||n==='medio'||n==='media')return coloredPill(value,'status-medium');if(n==='low'||n==='bajo'||n==='baja')return coloredPill(value,'status-low')}
 return value;
}
function render(k){let a=rows(k),c=configs[k],body=document.querySelector(`[data-body="${k}"]`);body.innerHTML=a.map(r=>`<tr>${c.row(r).map((v,i)=>{const shown=formatCell(k,i,v);return `<td>${i===0?'<b>'+shown+'</b>':shown}</td>`}).join('')}</tr>`).join('');document.querySelectorAll(`th[data-sort-kind="${k}"] .sort-mark`).forEach((m,i)=>m.textContent=sortState[k]?.index===i?(sortState[k].dir==='asc'?'▲':'▼'):'');let page=body.closest('.page'),kp=page.querySelectorAll('[data-kpi]');if(k==='coverage')renderCoverageChart(a);if(kp.length){let vals=[a.length];if(k==='requirements')vals.push(a.filter(r=>r.priority==='critical').length,a.filter(r=>r.priority==='high').length,new Set(a.map(r=>r.module)).size);if(k==='tests')vals.push(a.filter(r=>r.via==='UI').length,a.filter(r=>r.via==='Service').length,new Set(a.map(r=>r.module)).size);if(k==='coverage')vals.push(a.filter(r=>r.diagnosis==='Correcto').length,a.filter(r=>r.verification==='Limitada').length,new Set(a.map(r=>r.module)).size);if(k==='questions')vals.push(a.filter(r=>r.status==='Abierta').length,a.filter(r=>r.status==='Cerrada').length,a.filter(r=>r.answer!=='—').length);if(k==='risks')vals.push(a.filter(r=>r.level==='Alto').length,a.filter(r=>r.level==='Medio').length);if(k==='evolutions')vals.push(a.filter(r=>r.status==='draft').length,a.filter(r=>r.gate==='pending').length,a.filter(r=>r.effort==='medium').length);if(k==='documents')vals.push(a.filter(r=>r.type==='Markdown').length,a.filter(r=>r.structured==='Sí').length,new Set(a.map(r=>r.area)).size);kp.forEach((e,i)=>e.textContent=vals[i]??'—')}}
function renderCoverageChart(rows){const order=['clients','vehicles','peces','albarans','factures','personal','nomines','shell','configuracio'];const labels={clients:'clients',vehicles:'vehicles',peces:'peces',albarans:'albarans',factures:'factures',personal:'personal',nomines:'nomines',shell:'shell',configuracio:'configuracio'};const grouped={};rows.forEach(r=>grouped[r.module]=(grouped[r.module]||0)+1);const max=Math.max(1,...Object.values(grouped));const chart=document.getElementById('coverageChart');if(chart)chart.innerHTML=order.filter(m=>grouped[m]).map(m=>`<div class="coverage-row"><span>${labels[m]}</span><div class="coverage-track"><div class="coverage-fill" style="width:${grouped[m]/max*100}%">${grouped[m]}</div></div><b>${grouped[m]}</b></div>`).join('');const visible=document.getElementById('covVisible'),covered=document.getElementById('covCovered'),limited=document.getElementById('covLimited'),percent=document.getElementById('covPercent');if(visible)visible.textContent=rows.length;if(covered)covered.textContent=rows.filter(r=>r.diagnosis==='Correcto').length;if(limited)limited.textContent=rows.filter(r=>r.verification==='Limitada').length;if(percent)percent.textContent=rows.length?Math.round(rows.filter(r=>r.diagnosis==='Correcto').length/rows.length*100)+'%':'0%'}
function drawSummary(){/* el resumen ahora se renderiza server-side; nada que hacer aqui */}
init();
